### ISSUE TITLE
Cursor blinking with rcarriga/nvim-notify

### ISSUE THREAD

**Issue by gegoune** [TimUntersberger/neogit#220]
### Description

Exactly the same as in #158 - after committing this time and if `rcarriga/nvim-notify` is enabled.

After commit is completed and notification displayed cursor is blinking very fast for the entire duration of when notification is displayed.

### Neovim version

v0.6.0-dev+96614f84a

### Operating system and version

macOS 11.5

### Steps to reproduce

1. `mkdir /tmp/test; cd /tmp/test/; git init; echo test > testfile; git add testfile`
2. `nvim --clean -u <minimal file from below>`
3. `:Neogit commit`
4. add message, save, quit,  confirm

### Expected behavior

Notification pops up and cursor blink as configured in terminal emulator (Alacritty) rate.

### Actual behavior

Cursor blinks very fast (like in #158) for the duration of when notification is displayed. Returns to normal after notification closes.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
vim.o.termguicolors = true
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'TimUntersberger/neogit',
        requires = {
          { 'nvim-lua/plenary.nvim' },
        },
        config = function()
          require('neogit').setup {
            disable_builtin_notifications = true,
          }
        end,
      },
      {
        'rcarriga/nvim-notify',
        config = function()
          require('notify').setup { stages = 'static' }
          vim.notify = require 'notify'
        end,
      },
      'folke/tokyonight.nvim',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print 'Installing neogit and dependencies.'
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[colorscheme tokyonight]]
```

**Comment by gegoune** [comment]
Ah, sorry, pressed submit by mistake. Minimal config is not working, nvim-notify is erroring with `Error running notification service: ...e/pack/packer/start/nvim-notify/lua/notify/util/init.lua:48: attempt to perform
arithmetic on a nil value` on
```viml
lua vim.notify("This is an error message", "error")
```

Trying to figure it out right now (@rcarriga, perhaps you know what the issue here is?)

**Comment by rcarriga** [comment]
I'm going to guess it's because your `Normal` highlight group doesn't have a foreground `guifg` colour

**Comment by gegoune** [comment]
@rcarriga Thank you! There was another `blend` problem after that which lead me to suspect colorscheme was messing it all up. Have updated with original post's minimal config (added tokyonight) and the bug is reproducible now.

**Comment by rcarriga** [comment]
Yep just tried myself and it was the use of colour names rather than hex values. Will be adding support, thanks for accidentally catching that :smile:

**Comment by rcarriga** [comment]
Just to weigh in here, I can't seem to reproduce. I'm going to guess this is because of terminal differences (I'm using kitty).

Based on this message https://github.com/TimUntersberger/neogit/issues/158#issuecomment-882837062 it seems like the problem is rapid redrawing, which nvim-notify does (a lot) in order to perform animations. I can see in the NeoGit code there are a number of "refreshes". My first guess would be these are the problem but since I can't reproduce I can't actually test that out

**Comment by TimUntersberger** [comment]
@gegoune can you try doing something like the following

```vim
autocmd User NeogitStatusRefresh echom refreshed
```

**Comment by gegoune** [comment]
Just tried, very interesting. Does not seem to be adding those messages to `:messages`.

**Comment by TimUntersberger** [comment]
@gegoune you can reproduce this by using the minimal config and also installing nvim-notify right?

**Comment by gegoune** [comment]
@TimUntersberger Correct, yes, minimal config provided reproduces the issue for me every time.

It might be the case that you need to have blinking cursor enabled in terminal emulator to see it. Did not try to set it to non blinking though.

**Comment by TimUntersberger** [comment]
@gegoune I tried to reproduce this, but I sadly can't. Could you record a small video of the blinking cursor?

**Comment by gegoune** [comment]
@TimUntersberger Please see it on this video, I have used minimal config from top post.

https://user-images.githubusercontent.com/69750637/135820489-b9e099d2-c755-4d9c-9f25-46d87f1fa7a4.mov

**Comment by TimUntersberger** [comment]
@gegoune can you show me your alacritty config? I sadly can't reproduce this even with the same terminal.

**Comment by gegoune** [comment]
@TimUntersberger 

```
import:
  - ~/.local/share/nvim/site/pack/packer/start/tokyonight.nvim/extras/alacritty_tokyonight_night.yml
env:
  TERM: alacritty
window:
  decorations: full
  startup_mode: Fullscreen
scrolling:
  history: 0
font:
  normal:
    family: Iosevka Nerd Font Mono
    style: Light
  bold:
    family: Iosevka Nerd Font Mono
    style: Medium
  italic:
    family: Iosevka Nerd Font Mono
    style: Light Italic
  bold_italic:
    family: Iosevka Nerd Font Mono
    style: Medium Italic
  size: 14.0
  offset:
    x: 0
    y: 2
  use_thin_strokes: true
selection:
  semantic_escape_chars: " ,`'\"|()[]{}<>\t="
  save_to_clipboard: true
cursor:
  style:
    blinking: Always
  blink_interval: 350
  unfocused_hollow: true
shell:
  program: /usr/local/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - main
alt_send_esc: true
mouse:
  hide_when_typing: true
key_bindings:
  # Doubt keys are relevant
```
